const Joi = require('joi');
const validImpactCores = ['Water', 'Earth', 'Energy', 'Social'];
const validSdgs = [
    'No poverty',
    'Zero hunger',
    'Good health & well-being',
    'Quality education',
    'Gender equality',
    'Clean water & sanitation',
    'Affordable & clean energy',
    'Decent work & economic growth',
    'Industry, innovation & infrastructure',
    'Reduced inequalities',
    'Sustainable cities & communities',
    'Responsible consumption & production',
    'Climate action',
    'Life below water',
    'Life on land',
    'Peace, justice & strong institutions',
    'Partnerships for the goals'
];
const validSdgSubTargets = [
    'Eradicate extreme poverty',
    'Reduce multidimensional poverty',
    'Social protection systems',
    'Equal economic rights and land access',
    'Resilience to climate shocks',
    'Mobilize development finance',
    'Pro-poor policy frameworks',
    'End hunger and ensure food access',
    'End malnutrition',
    'Double smallholder productivity',
    'Sustainable food production',
    'Genetic diversity conservation',
    'Agricultural investment',
    'Reduce agricultural subsidies',
    'Stabilize food prices',
    'Reduce maternal mortality',
    'End preventable child deaths',
    'End AIDS, TB, malaria epidemics',
    'Reduce NCD premature mortality',
    'Prevent substance abuse',
    'Reduce road traffic deaths',
    'Universal sexual/reproductive health',
    'Universal health coverage',
    'Reduce pollution and hazardous chemicals',
    'Tobacco control policies',
    'Vaccine-preventable diseases',
    'Health workforce training',
    'Early warning health systems',
    'Primary education completion',
    'Quality early childhood development',
    'Technical and vocational education',
    'Youth employment skills',
    'Eliminate education disparities',
    'Sustainable development education',
    'Safe and inclusive learning environments',
    'Scholarships for developing countries',
    'Qualified teachers training',
    'End discrimination against women',
    'Eliminate violence against women',
    'Eliminate harmful practices',
    'Childcare and domestic support',
    'Women\'s leadership participation',
    'Sexual and reproductive health rights',
    'Equal economic resource access',
    'Women\'s enabling technology use',
    'Gender equality policies',
    'Universal clean water access',
    'Adequate sanitation and hygiene',
    'Improve water quality',
    'Increase water-use efficiency',
    'Transboundary water cooperation',
    'Protect water-related ecosystems',
    'Water/sanitation development finance',
    'Local community water management',
    'Universal modern energy access',
    'Increase renewable energy share',
    'Double energy efficiency improvement',
    'Clean energy research investment',
    'Sustainable energy infrastructure',
    'Increased worker productivity',
    'Decent work for all',
    'End forced labor and child labor',
    'Stop illicit financial flows',
    'Youth productive employment',
    'Domestic financial institutions',
    'Aid for Trade support',
    'Youth employment strategies',
    'Resilient infrastructure',
    'Inclusive industrialization',
    'SME finance and innovation',
    'Sustainable industry practices',
    'Science and technology workers',
    'Capacity-building investment',
    'Technology capacity strengthening',
    'ICT access in developing countries',
    'Bottom 40% income growth',
    'Social and economic inclusion',
    'Equal opportunity and access',
    'Sustainable development policies',
    'Financial market regulation',
    'Domestic resource mobilization',
    'International cooperation finance',
    'Safe and orderly migration',
    'Special trade benefits for LDCs',
    'Official development assistance',
    'Migrant remittance costs reduction',
    'Sustainable city policies',
    'Sustainable transport systems',
    'Safe, affordable housing',
    'Cultural and natural heritage',
    'Reduce disaster deaths',
    'Improve city air quality',
    'Green and public spaces',
    'Urban-rural economic linkages',
    'Cities resilience planning',
    'Sustainable buildings',
    'Household waste reduction',
    'Waste prevention and recycling',
    'Chemical and waste management',
    'Waste generation reduction',
    'Corporate sustainable practices',
    'Sustainable procurement',
    'Sustainable development awareness',
    'Technology transfer investments',
    'Plastic waste prevention',
    'Sustainable tourism monitoring',
    'Fossil fuel subsidies elimination',
    'Climate resilience capacity',
    'National climate adaptation plans',
    'Climate education and awareness',
    'Climate finance mobilization',
    'Climate action in vulnerable countries',
    'Prevent marine pollution',
    'Protect marine ecosystems',
    'Reduce ocean acidification',
    'Sustainable fishing',
    'Coastal and marine protection',
    'Fishery subsidies elimination',
    'Sustainable fisheries benefits',
    'Ocean research and capacity',
    'Small-scale fishers market access',
    'UNCLOS conservation implementation',
    'Terrestrial ecosystem conservation',
    'Forest protection and reforestation',
    'Land degradation restoration',
    'Mountain ecosystem conservation',
    'Threatened species protection',
    'Genetic resources benefit sharing',
    'End poaching and trafficking',
    'Invasive species management',
    'Ecosystem and biodiversity planning',
    'Ecosystem conservation finance',
    'Sustainable forest management',
    'Anti-poaching operations',
    'Reduce violence everywhere',
    'Protect children from violence',
    'Rule of law and justice access',
    'Stop illicit arms and flows',
    'Reduce corruption and bribery',
    'Effective and accountable institutions',
    'Democratic participation',
    'Global governance participation',
    'Legal identity for all',
    'Public access to information',
    'Institutional capacity-building',
    'Non-discriminatory law enforcement',
    'Domestic revenue collection',
    'ODA commitments fulfillment',
    'Finance for developing countries',
    'Technology transfer projects',
    'Science and technology cooperation',
    'Technology bank operationalization',
    'Sustainable technology deployment',
    'Capacity-building initiatives',
    'Developing countries export growth',
    'Duty-free quota-free market access',
    'Global macroeconomic stability',
    'SDG policy coherence',
    'Respect national SDG policies',
    'Multi-stakeholder partnerships',
    'Public-private partnerships',
    'High-quality SDG data',
    'SDG progress measurements',
    'SDG policy coherence',
    'SDG knowledge networks',
    'Technology capacity-building',
    'South-South cooperation',
    'Least developed countries technology',
    'Global SDG partnerships'
];
const sdgToSubTargets = {
    'No poverty': [
        'Eradicate extreme poverty',
        'Reduce multidimensional poverty',
        'Social protection systems',
        'Equal economic rights and land access',
        'Resilience to climate shocks',
        'Mobilize development finance',
        'Pro-poor policy frameworks'
    ],
    'Zero hunger': [
        'End hunger and ensure food access',
        'End malnutrition',
        'Double smallholder productivity',
        'Sustainable food production',
        'Genetic diversity conservation',
        'Agricultural investment',
        'Reduce agricultural subsidies',
        'Stabilize food prices'
    ],
    'Good health & well-being': [
        'Reduce maternal mortality',
        'End preventable child deaths',
        'End AIDS, TB, malaria epidemics',
        'Reduce NCD premature mortality',
        'Prevent substance abuse',
        'Reduce road traffic deaths',
        'Universal sexual/reproductive health',
        'Universal health coverage',
        'Reduce pollution and hazardous chemicals',
        'Tobacco control policies',
        'Vaccine-preventable diseases',
        'Health workforce training',
        'Early warning health systems'
    ],
    'Quality education': [
        'Primary education completion',
        'Quality early childhood development',
        'Technical and vocational education',
        'Youth employment skills',
        'Eliminate education disparities',
        'Sustainable development education',
        'Safe and inclusive learning environments',
        'Scholarships for developing countries',
        'Qualified teachers training'
    ],
    'Gender equality': [
        'End discrimination against women',
        'Eliminate violence against women',
        'Eliminate harmful practices',
        'Childcare and domestic support',
        'Women\'s leadership participation',
        'Sexual and reproductive health rights',
        'Equal economic resource access',
        'Women\'s enabling technology use',
        'Gender equality policies'
    ],
    'Clean water & sanitation': [
        'Universal clean water access',
        'Adequate sanitation and hygiene',
        'Improve water quality',
        'Increase water-use efficiency',
        'Transboundary water cooperation',
        'Protect water-related ecosystems',
        'Water/sanitation development finance',
        'Local community water management'
    ],
    'Affordable & clean energy': [
        'Universal modern energy access',
        'Increase renewable energy share',
        'Double energy efficiency improvement',
        'Clean energy research investment',
        'Sustainable energy infrastructure'
    ],
    'Decent work & economic growth': [
        'Increased worker productivity',
        'Decent work for all',
        'End forced labor and child labor',
        'Stop illicit financial flows',
        'Youth productive employment',
        'Domestic financial institutions',
        'Aid for Trade support',
        'Youth employment strategies'
    ],
    'Industry, innovation & infrastructure': [
        'Resilient infrastructure',
        'Inclusive industrialization',
        'SME finance and innovation',
        'Sustainable industry practices',
        'Science and technology workers',
        'Capacity-building investment',
        'Technology capacity strengthening',
        'ICT access in developing countries'
    ],
    'Reduced inequalities': [
        'Bottom 40% income growth',
        'Social and economic inclusion',
        'Equal opportunity and access',
        'Sustainable development policies',
        'Financial market regulation',
        'Domestic resource mobilization',
        'International cooperation finance',
        'Safe and orderly migration',
        'Special trade benefits for LDCs',
        'Official development assistance',
        'Migrant remittance costs reduction'
    ],
    'Sustainable cities & communities': [
        'Sustainable city policies',
        'Sustainable transport systems',
        'Safe, affordable housing',
        'Cultural and natural heritage',
        'Reduce disaster deaths',
        'Improve city air quality',
        'Green and public spaces',
        'Urban-rural economic linkages',
        'Cities resilience planning',
        'Sustainable buildings'
    ],
    'Responsible consumption & production': [
        'Household waste reduction',
        'Waste prevention and recycling',
        'Chemical and waste management',
        'Waste generation reduction',
        'Corporate sustainable practices',
        'Sustainable procurement',
        'Sustainable development awareness',
        'Technology transfer investments',
        'Plastic waste prevention',
        'Sustainable tourism monitoring',
        'Fossil fuel subsidies elimination'
    ],
    'Climate action': [
        'Climate resilience capacity',
        'National climate adaptation plans',
        'Climate education and awareness',
        'Climate finance mobilization',
        'Climate action in vulnerable countries'
    ],
    'Life below water': [
        'Prevent marine pollution',
        'Protect marine ecosystems',
        'Reduce ocean acidification',
        'Sustainable fishing',
        'Coastal and marine protection',
        'Fishery subsidies elimination',
        'Sustainable fisheries benefits',
        'Ocean research and capacity',
        'Small-scale fishers market access',
        'UNCLOS conservation implementation'
    ],
    'Life on land': [
        'Terrestrial ecosystem conservation',
        'Forest protection and reforestation',
        'Land degradation restoration',
        'Mountain ecosystem conservation',
        'Threatened species protection',
        'Genetic resources benefit sharing',
        'End poaching and trafficking',
        'Invasive species management',
        'Ecosystem and biodiversity planning',
        'Ecosystem conservation finance',
        'Sustainable forest management',
        'Anti-poaching operations'
    ],
    'Peace, justice & strong institutions': [
        'Reduce violence everywhere',
        'Protect children from violence',
        'Rule of law and justice access',
        'Stop illicit arms and flows',
        'Reduce corruption and bribery',
        'Effective and accountable institutions',
        'Democratic participation',
        'Global governance participation',
        'Legal identity for all',
        'Public access to information',
        'Institutional capacity-building',
        'Non-discriminatory law enforcement'
    ],
    'Partnerships for the goals': [
        'Domestic revenue collection',
        'ODA commitments fulfillment',
        'Finance for developing countries',
        'Technology transfer projects',
        'Science and technology cooperation',
        'Technology bank operationalization',
        'Sustainable technology deployment',
        'Capacity-building initiatives',
        'Developing countries export growth',
        'Duty-free quota-free market access',
        'Global macroeconomic stability',
        'SDG policy coherence',
        'Respect national SDG policies',
        'Multi-stakeholder partnerships',
        'Public-private partnerships',
        'High-quality SDG data',
        'SDG progress measurements',
        'SDG knowledge networks',
        'Technology capacity-building',
        'South-South cooperation',
        'Least developed countries technology',
        'Global SDG partnerships'
    ]
};

const validBountyTypes = [
    'GHG Removal',
    'Data Science',
    'Learning',
    'Harvesting',
    'Scouting',
    'Code',
    'Design',
    'Volunteer',
    'Regenerate',
    'General',
    'Promotion',
    'Survey',
    'Training',
    'Content',
    'Restoration',
    'Gardening',
    'Validate',
    'Research',
    'Writing',
    'Registration',
    'Community',
    'Recycle',
    'Funding'
];
const supportedBlockchains = [ 'arbitrum', 'base', 'celo', 'optimism', 'optimism sepolia' ];
const blockchainDetails = {
    'arbitrum': {
        image: 'assets/arbitrum.png',
        chainId: 42161
    },
    'base': {
        image: 'assets/base.png',
        chainId: 8453
    },
    'celo': {
        image: 'assets/celo.png',
        chainId: 42220
    },
    'optimism': {
        image: 'assets/optimism.png',
        chainId: 10
    },
    'optimism sepolia': {
        image: 'assets/optimism.png',
        chainId: 11155420
    }
};
const evmAddressRegex = new RegExp('^0x[a-fA-F0-9]{40}$');

/*
    "projectName": "Sample Project",
	"projectStartDate": "2025-09-18T13:40:40",
    "projectEndDate": "2025-09-25T13:40:40",
    "backerName": "Sample Organisation",
    "backerLogo": "https://orgwebsite.org/sample_image.png",
    "projectDescription": "This project was carried out in Bengaluru to promote rainwater harvesting. Over 20000 households setup rainwater harvesting which can potentially lead to 4000000 litres of water being harvested",
    "totalFundsDeployedUSD": 50000,
    "totalImpactPointsAllocated": 2000000,
    "impactCoresAffected": [ "Water", "Earth", "Energy", "Social"],
    "SDGsAffected": [ "zero hunger", "no poverty" ],
    "bountyTypeWisePassAndFailCount": [
        {
            "type": "Design",
            "passCount": 20,
            "failCount": 5
        },
        {
            "type": "Code",
            "passCount": 23,
            "failCount": 2
        }
    ],
    "paymentTransactionBlockchain": "arbitrum",
    "paymentTransactionHash": "0xsomerandomtransactionhash",
    "paymentTokenAddress": "0xSomerandomaddress",
    "mintBlockchain": "optimism sepolia",
    "receiverAddress": "0xsomerandomaddress"
*/
const requestMinting = {
    body: Joi.object().keys({
        projectName: Joi.string().required(),
        projectStartDate: Joi.date().required(),
        projectEndDate: Joi.date().required(),
        backerName: Joi.string().required(),
        backerLogo: Joi.string().uri().required(),
        projectDescription: Joi.string().required(),
        totalFundsDeployedUSD: Joi.number().required(),
        totalImpactPointsAllocated: Joi.number().required(),
        impactCoresAffected: Joi.array().items(Joi.string().valid(...validImpactCores)).min(1).required(),
        SDGsAffected: Joi.array().items(Joi.string().valid(...validSdgs)).min(1).required(),
        bountyTypeWisePassAndFailCount: Joi.array().items(Joi.object().keys({
            type: Joi.string().valid(...validBountyTypes).required(),
            passCount: Joi.number().integer().min(0).required(),
            failCount: Joi.number().integer().min(0).required()
        }).custom((value, helpers) => {
            if (value.passCount === 0 && value.failCount === 0) {
                return helpers.error("a passed bounty type must have at least one submission")
            }
            return value;
        })).min(1).required(),
        paymentTransactionBlockchain: Joi.string().valid(...supportedBlockchains).required(),
        paymentTransactionHash: Joi.string().required(),
        paymentTokenAddress: Joi.string().pattern(evmAddressRegex).required(),
        mintBlockchain: Joi.string().valid(...supportedBlockchains).required(),
        receiverAddress: Joi.string().pattern(evmAddressRegex).required()
    })
};

const requestMintingV2 = {
    body: Joi.object().keys({
        projectName: Joi.string().required(),
        projectStartDate: Joi.date().required(),
        projectEndDate: Joi.date().required(),
        backerName: Joi.string().required(),
        backerLogo: Joi.string().uri().required(),
        projectDescription: Joi.string().required(),
        totalFundsDeployedUSD: Joi.number().required(),
        impactCoresAffected: Joi.array().items(Joi.string().valid(...validImpactCores)).min(1).required(),
        impactBrief: Joi.object().keys({
            SDG: Joi.string().valid(...validSdgs),
            subTarget: Joi.string().valid(...validSdgSubTargets),
            impactIndicator: Joi.string().required()
        }),
        paymentTransactionBlockchain: Joi.string().valid(...supportedBlockchains).required(),
        paymentTransactionHash: Joi.string().required(),
        paymentTokenAddress: Joi.string().pattern(evmAddressRegex).required(),
        mintBlockchain: Joi.string().valid(...supportedBlockchains).required(),
        receiverAddress: Joi.string().pattern(evmAddressRegex).required()
    })
};

const fetchMintStatus = {
    query: Joi.object().keys({
        requestId: Joi.string().required()
    })
};

module.exports = {
    requestMinting,
    requestMintingV2,
    fetchMintStatus,
    validImpactCores,
    validSdgs,
    sdgToSubTargets,
    blockchainDetails
};