const ethers = require("ethers")

/**
 * Verifies whether the specified signature was generated by signing of the specified message by the specified EVM address.
 * @param {string} evmAddress - EVM address used for signing the message.
 * @param {string} message - Original message used to generate the signature.
 * @param {string} signature - Generated signature.
 * @returns {boolean}
 */
const verifySignature = (evmAddress, message, signature) => {
    // Ensure the address is checksummed (properly formatted)
    const checksumAddress = ethers.getAddress(evmAddress);
    // Recover the signer's address from the signature and message
    const signerAddress = ethers.verifyMessage(message, signature);
    // Compare the recovered address with the original address
    return signerAddress.toLowerCase() === checksumAddress.toLowerCase();
};

module.exports = verifySignature;